- name: "Configurando red..."
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: Reiniciando la maquina...
  ansible.builtin.reboot:

